
runtime: python39

instance_class: F1

# Automatic scaling example
# https://cloud.google.com/appengine/docs/standard/python3/config/appref#automatic_scaling
automatic_scaling:
  # keep this to 1 to stay in the free tier of app engine
  max_instances: 1

entrypoint: uwsgi --http-socket :$PORT --wsgi-file main.py --callable app --master --processes 1 --threads 2

handlers:
- url: /.*
  # force https on all requests
  secure: always
  script: auto
